### ISSUE TITLE
Minified file is missing version

### ISSUE THREAD

**Issue by adgoncal** [openseadragon/site-build#165] opened 2016-12-21 23:44 UTC
```javaScript
a.version={versionStr:"<%= osdVersion.versionStr %>",major:parseInt("<%= osdVersion.major %>",10),minor:parseInt("<%= osdVersion.minor %>",10),revision:parseInt("<%= osdVersion.revision %>",10)
```

https://github.com/openseadragon/site-build/blob/v2.2.1/built-openseadragon/openseadragon/openseadragon.min.js

**Comment by adgoncal** [comment] 2016-12-21 23:46
It is missing version in 2.2.0 also. 
2.1.0 is fine.

**Comment by iangilman** [comment] 2016-12-22 17:52
@adgoncal Good catch!

Looks like it happened here, since we're no longer uglifying the concatted version (which is where the `process` flag fills in the grunt template bits). 

https://github.com/openseadragon/openseadragon/commit/44343610336c952a081ff21e5183c2758efc2a38

That's part of https://github.com/openseadragon/openseadragon/pull/831 by @avandecreme. In the discussion there, it sounds like it would be fine to go back to using the concatted version instead of the original sources. I took a look at https://github.com/gruntjs/grunt-contrib-uglify and it doesn't seem to have a `process` feature.

@avandecreme What do you think?

**Comment by avandecreme** [comment] 2016-12-23 09:08
Ha yes sorry for having broken that. It was already reported in https://github.com/openseadragon/openseadragon/issues/1024
I will make sure to fix that for the next release.

**Comment by iangilman** [comment] 2016-12-28 18:16
@avandecreme Excellent, thank you!

**Comment by iangilman** [comment] 2016-12-28 18:17
I guess we can close this as a duplicate of the other bug. @adgoncal thank you for filing this, though, to remind us!

**Closed by iangilman** 2016-12-28 18:17 UTC
Labels: bug
